/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inf.pucp.edu.pe.vista.simulacion;

/**
 *
 * @author juancarlos
 */
public class VentanaDeInformacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaDeInformacion2
     */
    public VentanaDeInformacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lZona = new javax.swing.JLabel();
        lPosicionX = new javax.swing.JLabel();
        lPosicionY = new javax.swing.JLabel();
        btnLeft = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();

        lZona.setText("Zona: ");

        lPosicionX.setText("Posicion X: ");

        lPosicionY.setText("Posicion Y: ");

        btnLeft.setText("Izquierda");
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnDown.setText("Abajo");
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });

        btnRight.setText("Derecha");
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnUp.setText("Arriba");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPosicionY)
                            .addComponent(lPosicionX)
                            .addComponent(lZona)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUp)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRight)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lZona)
                .addGap(18, 18, 18)
                .addComponent(lPosicionX)
                .addGap(18, 18, 18)
                .addComponent(lPosicionY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeft)
                    .addComponent(btnDown)
                    .addComponent(btnRight))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        if(MenuPrincipalSimulacion.posicionRelativaY>0){
                MenuPrincipalSimulacion.posicionRelativaY-=MenuPrincipalSimulacion.alto;
                MenuPrincipalSimulacion.zonaActual-=MenuPrincipalSimulacion.dimensionXMapa/MenuPrincipalSimulacion.ancho;
                }
                lZona.setText("Zona:  "+ MenuPrincipalSimulacion.zonaActual);
                lPosicionX.setText("Posicion X: "+ MenuPrincipalSimulacion.posicionRelativaX*10);
                lPosicionY.setText("Posicion Y: "+ MenuPrincipalSimulacion.posicionRelativaY*10);
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        if(MenuPrincipalSimulacion.posicionRelativaX>0){
                MenuPrincipalSimulacion.posicionRelativaX-=MenuPrincipalSimulacion.ancho;
                MenuPrincipalSimulacion.zonaActual-=1;
                }
                
                lZona.setText("Zona:  "+ MenuPrincipalSimulacion.zonaActual);
                lPosicionX.setText("Posicion X: "+ MenuPrincipalSimulacion.posicionRelativaX*10);
                lPosicionY.setText("Posicion Y: "+ MenuPrincipalSimulacion.posicionRelativaY*10);
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        if(MenuPrincipalSimulacion.posicionRelativaY<=14400){
                MenuPrincipalSimulacion.posicionRelativaY+=MenuPrincipalSimulacion.alto;
                MenuPrincipalSimulacion.zonaActual+=MenuPrincipalSimulacion.dimensionXMapa/MenuPrincipalSimulacion.ancho;
                }
                 
                lZona.setText("Zona:  "+ MenuPrincipalSimulacion.zonaActual);
                lPosicionX.setText("Posicion X: "+ MenuPrincipalSimulacion.posicionRelativaX*10);
                lPosicionY.setText("Posicion Y: "+ MenuPrincipalSimulacion.posicionRelativaY*10);
    }//GEN-LAST:event_btnDownActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        if(MenuPrincipalSimulacion.posicionRelativaX<=22400){
                MenuPrincipalSimulacion.posicionRelativaX+=MenuPrincipalSimulacion.ancho;
                MenuPrincipalSimulacion.zonaActual+=1;
                }
                
                lZona.setText("Zona:  "+ MenuPrincipalSimulacion.zonaActual);
                lPosicionX.setText("Posicion X: "+ MenuPrincipalSimulacion.posicionRelativaX*10);
                lPosicionY.setText("Posicion Y: "+ MenuPrincipalSimulacion.posicionRelativaY*10);
    }//GEN-LAST:event_btnRightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnUp;
    private javax.swing.JLabel lPosicionX;
    private javax.swing.JLabel lPosicionY;
    private javax.swing.JLabel lZona;
    // End of variables declaration//GEN-END:variables
}
