/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inf.pucp.edu.pe.vista.seguridad;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.border.EmptyBorder;
import inf.pucp.edu.pe.vista.principal.*;

import java.awt.Color;

/**
 *
 * @author JuanCarlos
 */
public class MenuPrincipalSeguridad extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalSeguridad
     */
    
    Color colorMenu = new Color(229, 232, 126);
            
    public MenuPrincipalSeguridad() {
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //this.setDefaultCloseOperation(MenuPrincipalSeguridad.EXIT_ON_CLOSE);
        //this.setLocationRelativeTo(null);
        //setBounds(400, 100, 550, 600);
        // p.setBorder(new EmptyBorder(5, 5, 5, 5));
        //p.setLayout(new BorderLayout(0, 0));
        //PanelImagenVentana p = new PanelImagenVentana();
        //setContentPane(p);
       // this.setBackground(Color.BLACK);
        this.setTitle("Menú Principal de Seguridad");
        initComponents();
        jMenuBar1.setBackground(colorMenu);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDesbloquearUsuario = new javax.swing.JMenuItem();
        mnuCambiarContraseña = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuAgregarUsuario = new javax.swing.JMenuItem();
        mnuEliminarUsuario = new javax.swing.JMenuItem();
        mnuModificarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuAgregarPerfil = new javax.swing.JMenuItem();
        mnuModificarPerfil = new javax.swing.JMenuItem();
        mnuEliminarPerfil = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuRegistroDeLog = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Usuario");

        mnuDesbloquearUsuario.setText("Desbloquear usuario");
        mnuDesbloquearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDesbloquearUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDesbloquearUsuario);

        mnuCambiarContraseña.setText("Cambiar contraseña");
        mnuCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCambiarContraseñaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCambiarContraseña);

        jMenu3.setText("Administrar usuario");

        mnuAgregarUsuario.setText("Agregar Usuario");
        mnuAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAgregarUsuario);

        mnuEliminarUsuario.setText("Eliminar Usuario");
        mnuEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEliminarUsuario);

        mnuModificarUsuario.setText("Modificar Usuario");
        mnuModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(mnuModificarUsuario);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Perfil");

        mnuAgregarPerfil.setText("Agregar Perfil");
        mnuAgregarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarPerfilActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAgregarPerfil);

        mnuModificarPerfil.setText("Modificar Perfil");
        mnuModificarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarPerfilActionPerformed(evt);
            }
        });
        jMenu2.add(mnuModificarPerfil);

        mnuEliminarPerfil.setText("Eliminar Perfil");
        mnuEliminarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarPerfilActionPerformed(evt);
            }
        });
        jMenu2.add(mnuEliminarPerfil);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Log");

        mnuRegistroDeLog.setText("Registro de Log");
        mnuRegistroDeLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroDeLogActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRegistroDeLog);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCambiarContraseñaActionPerformed
        
        CambiarContraseña cc= new CambiarContraseña();
        this.add(cc);
        cc.setVisible(true);
    }//GEN-LAST:event_mnuCambiarContraseñaActionPerformed

    private void mnuDesbloquearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDesbloquearUsuarioActionPerformed
        // TODO add your handling code here:
        DesbloquearUsuario du= new DesbloquearUsuario();
        this.add(du);
        du.setVisible(true);
    }//GEN-LAST:event_mnuDesbloquearUsuarioActionPerformed

    private void mnuAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        AgregarUsuario au= new AgregarUsuario();
        this.add(au);
        au.setVisible(true);
    }//GEN-LAST:event_mnuAgregarUsuarioActionPerformed

    private void mnuEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarUsuarioActionPerformed
        // TODO add your handling code here:
        EliminarUsuario eu= new EliminarUsuario();
        this.add(eu);
        eu.setVisible(true);
    }//GEN-LAST:event_mnuEliminarUsuarioActionPerformed

    private void mnuModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarUsuarioActionPerformed
        // TODO add your handling code here:
        ModificarUsuario mu= new ModificarUsuario();
        this.add(mu);
        mu.setVisible(true);
    }//GEN-LAST:event_mnuModificarUsuarioActionPerformed

    private void mnuAgregarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarPerfilActionPerformed
        AgregarPerfil ap= new AgregarPerfil();
        this.add(ap);
        ap.setVisible(true);
    }//GEN-LAST:event_mnuAgregarPerfilActionPerformed

    private void mnuModificarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarPerfilActionPerformed
        ModificarPerfil mp= new ModificarPerfil();
        this.add(mp);
        mp.setVisible(true);
    }//GEN-LAST:event_mnuModificarPerfilActionPerformed

    private void mnuEliminarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarPerfilActionPerformed
        EliminarPerfil ep= new EliminarPerfil();
        this.add(ep);
        ep.setVisible(true);
    }//GEN-LAST:event_mnuEliminarPerfilActionPerformed

    private void mnuRegistroDeLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroDeLogActionPerformed
        RegistroDeLog rdl= new RegistroDeLog();
        this.add(rdl);
        rdl.setVisible(true);
    }//GEN-LAST:event_mnuRegistroDeLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipalSeguridad ms= new MenuPrincipalSeguridad();
                
                ms.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAgregarPerfil;
    private javax.swing.JMenuItem mnuAgregarUsuario;
    private javax.swing.JMenuItem mnuCambiarContraseña;
    private javax.swing.JMenuItem mnuDesbloquearUsuario;
    private javax.swing.JMenuItem mnuEliminarPerfil;
    private javax.swing.JMenuItem mnuEliminarUsuario;
    private javax.swing.JMenuItem mnuModificarPerfil;
    private javax.swing.JMenuItem mnuModificarUsuario;
    private javax.swing.JMenuItem mnuRegistroDeLog;
    // End of variables declaration//GEN-END:variables
}
