/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inf.pucp.edu.pe.vista.reporte;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.border.EmptyBorder;
import inf.pucp.edu.pe.vista.principal.PanelImagen;
import inf.pucp.edu.pe.vista.principal.PanelImagenVentana;
/**
 *
 * @author JuanCarlos
 */
public class MenuPrincipalReporte extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalReporte
     */
    public MenuPrincipalReporte() {
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        //this.setLocationRelativeTo(null);
        //setBounds(400, 100, 550, 600);
        //PanelImagenVentana p = new PanelImagenVentana();
        //p.setBorder(new EmptyBorder(5, 5, 5, 5));
      //  p.setLayout(new BorderLayout(0, 0));
        //setContentPane(p);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuVehiculosPorVia = new javax.swing.JMenuItem();
        mnuSemaforo = new javax.swing.JMenuItem();
        mnuVolumenDeAutos = new javax.swing.JMenuItem();
        mnuCantidadDeOlasVerdes = new javax.swing.JMenuItem();
        mnuVelocidadPromedio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenu1.setText("Reporte");
        jMenu1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jMenu1AncestorRemoved(evt);
            }
        });

        mnuVehiculosPorVia.setText("Vehiculos por via");
        mnuVehiculosPorVia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVehiculosPorViaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVehiculosPorVia);

        mnuSemaforo.setText("Semaforo");
        mnuSemaforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSemaforoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSemaforo);

        mnuVolumenDeAutos.setText("Volumen de autos");
        mnuVolumenDeAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVolumenDeAutosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVolumenDeAutos);

        mnuCantidadDeOlasVerdes.setText("Cantidad de olas verdes");
        mnuCantidadDeOlasVerdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCantidadDeOlasVerdesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCantidadDeOlasVerdes);

        mnuVelocidadPromedio.setText("Velocidad promedio");
        mnuVelocidadPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVelocidadPromedioActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVelocidadPromedio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenu1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1AncestorRemoved

    private void mnuVehiculosPorViaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVehiculosPorViaActionPerformed
        
        ReporteVehiculosPorVia rvv= new ReporteVehiculosPorVia();
        this.add(rvv);
        rvv.setVisible(true);
    }//GEN-LAST:event_mnuVehiculosPorViaActionPerformed

    private void mnuSemaforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSemaforoActionPerformed
        
        ReporteDeInformacionDeLosSemaforos ris=new ReporteDeInformacionDeLosSemaforos();
        this.add(ris);
        ris.setVisible(true);
    }//GEN-LAST:event_mnuSemaforoActionPerformed

    private void mnuVolumenDeAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVolumenDeAutosActionPerformed
        
        ReporteDeVolumenDeAutos rva= new ReporteDeVolumenDeAutos();
        this.add(rva);
        rva.setVisible(true);
    }//GEN-LAST:event_mnuVolumenDeAutosActionPerformed

    private void mnuCantidadDeOlasVerdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCantidadDeOlasVerdesActionPerformed
        
        ReporteDeCantidadDeOlasVerdes rcov= new ReporteDeCantidadDeOlasVerdes();
        this.add(rcov);
        rcov.setVisible(true);
    }//GEN-LAST:event_mnuCantidadDeOlasVerdesActionPerformed

    private void mnuVelocidadPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVelocidadPromedioActionPerformed
        
        ReporteDeVelocidadPromedioDeAutos rvpa = new ReporteDeVelocidadPromedioDeAutos();
        this.add(rvpa);
        rvpa.setVisible(true);
    }//GEN-LAST:event_mnuVelocidadPromedioActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCantidadDeOlasVerdes;
    private javax.swing.JMenuItem mnuSemaforo;
    private javax.swing.JMenuItem mnuVehiculosPorVia;
    private javax.swing.JMenuItem mnuVelocidadPromedio;
    private javax.swing.JMenuItem mnuVolumenDeAutos;
    // End of variables declaration//GEN-END:variables
}
